title: Matthew Wilson
#author: Matthew Wilson
email: mattwilsonmbw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    junior in computer engineering, university of utah. interested in robotics and deep (reinforcement) learning


twitter_username: matwilso
github_username:  matwilso
disqus:
    shortname: "https-matwilso-github-io"
google_analytics: "UA-89794815-1"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - blog.md
 # - about.md
 # - projects.md
 - personal.md
 # - hacks.md

# Build settings
markdown: kramdown
theme: minima
include:
    - _pages
    - _drafts
exclude:
  - Gemfile
  - Gemfile.lock
